### ISSUE TITLE
Pythagorean error

### ISSUE THREAD

**Issue by AndresF49** [FB-18-19-PreAP-CS/math-helper-rachelh2071#4]
Entering in the third side of a triangle, even though it tells you to enter a 0 for the side you are looking for, the program gives you a side that does not make sense. For example, if entering in side a: 4, b: 5, c: 6, it gives you an answer of 6.4. To me, it does not makes sense. I feel that the program should give you an error instead of showing this answer, telling you to re-enter your input.

**Comment by rachelh2071** [comment]
I fixed it. It shows an error now when none of the values are 0
